TPC /L /M /E%1 VISION.PAS /$I- /$F+ /$O+ /$R- /$S- /$N- /$A- /$E- /$D- /$V- /$B-
TPC /L /M /E%1 CONFIG.PAS /$I- /$F+ /$O+ /$R- /$S- /$N- /$A- /$E- /$D- /$V- /$B-
TPC /L /M /E%1 UE.PAS /$I- /$F+ /$O+ /$R- /$S- /$N- /$A- /$E- /$D- /$V- /$B-
TPC /L /M /E%1 STRINGS.PAS /$I- /$F+ /$O+ /$R- /$S- /$N- /$A- /$E- /$D- /$V- /$B-
TPC /L /M /E%1 PROTEDIT.PAS /$I- /$F+ /$O+ /$R- /$S- /$N- /$A- /$E- /$D- /$V- /$B-
TPC /L /M /E%1 MENUEDIT.PAS /$I- /$F+ /$O+ /$R- /$S- /$N- /$A- /$E- /$D- /$V- /$B-
TPC /L /M /E%1 CONFIG.PAS /$I- /$F+ /$O+ /$R- /$S- /$N- /$A- /$E- /$D- /$V- /$B-
TPC /L /M /E%1 TOPTEN.PAS /$I- /$F+ /$O+ /$R- /$S- /$N- /$A- /$E- /$D- /$V- /$B-
